name: CI
- task: Ansible@0
  inputs:
    ansibleInterface: 'remoteMachine'
    connectionOverSsh: 'ansibleVmssh'
    playbookSourceRemoteMachine: 'ansibleMachine'
    playbookPathAnsibleMachineOnRemoteMachine: '~/ansible_main/playbooks/'
    inventoriesRemoteMachine: 'noInventory'

# Run this workflow every time a commit is pushed to main or a pull request is opened against main
on: [push,pull_request]
#push:
 #   branches: [ main ]
#pull_request:
 #   branches: [ main ]

jobs:
    build:
        name: Call Azure Pipeline
        runs-on: ubuntu-latest
        steps:
        - name: Azure Pipelines Action
          uses: Azure/pipelines@v1
          with:
            azure-devops-project-url: https://dev.azure.com/avinashjha0266/test_ansible
            azure-pipeline-name: 'AnsiblePipeline'
            azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
